import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

// eslint-config-next@16 exports flat configs natively; no FlatCompat needed.
const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "build/**",
      "data/**",
      "*.tsbuildinfo",
      // generated by Next.js build; not tracked in git
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
